### PR TITLE
Add 2.1 to the django version list

### LINKED ISSUE #519: Add django 2.1 to the available version options
* Date you used Cookiecutter DjangoPackage: 08/17/2018
* Cookiecutter version used, if known: 1.6.0
* Python version: 2.7
* Operating System: Mac OS Mojave (Beta)

### Description

I tried to enter Django 2.1 as a valid version for my package. The cookiecutter failed. Since Django 2.1 has now been released, this should not occur.

### What I Did

```sh
...
django_versions [1.11,2.0]: 1.11,2.0,2.1
...
ERROR:pre_gen_project:Invalid Django version "2.1".
ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

### PR DESCRIPTION
**Pull request by joshua-s**
Fix #519

### CODE REVIEW

**Comment by jonathan-s** [comment]
Hi @joshua-s, thanks for your PR. There are a few other changes that needs to happen. If you search for `django_versions` in the repo you'll see what other changes need to be made.

**Comment by joshua-s** [comment]
@jonathan-s updated!

**Comment by jonathan-s** [comment]
@joshua-s Thanks for the update! And yes, I would agree with you, you're welcome to contribute support for 2.2 and 3.0 

If you feel up to it it would be good to remove unsupported versions as well. Django 2.0 reached end of life April 2019. https://docs.djangoproject.com/en/3.0/releases/2.0/#python-compatibility

**Comment by jonathan-s** [comment]
I got in touch with travis, you need to set the distribution to xenial to
be able to use python 3.7

**Comment by jonathan-s** [comment]
I'm going to merge this and fix the other things I mentioned in a separate PR. Thanks a lot for contributing @joshua-s, if you find any more time to improve other things, any help will be gracefully accepted. :)

**Comment by joshua-s** [comment]
Thanks @jonathan-s

**Pull request merged**
