### PR TITLE
Fixing test app settings and startup

### PR DESCRIPTION
**Pull request by luizanao**
This is fixing a wrong placed `wgsi.py` and poiting the settings to the correct place.
Now, people should be good to trust in the test app README file

### CODE REVIEW

**Comment by jonathan-s** [comment]
@luizanao Would you mind doing a git commit --amend and then force pushing the PR. It seems like Travis is a bit stuck.

**Comment by luizanao** [comment]
it's queue again and seems to be stuck. I will re-try later on.

**Comment by luizanao** [comment]
Seems to be good to go now @jonathan-s . thanks for assist on it ;)

**Comment by jonathan-s** [comment]
Thanks for contributing :)

**Pull request merged**
